---
title: "Simulation"
author: "Valerie McIlvaine"
date: "7/20/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```


```{r Begin simulation coin toss, binomial}
#tossing a coin

coin_toss= c("Heads", "Tails")
set.seed(1)
y=sample(coin_toss, 10, replace = TRUE ) #take sample of 10
length(y[y=="Heads"])
y

#replicate tosses 50 times 
replicate(50, sample( coin_toss, 10, replace= TRUE))
first=replicate(50, length(sample(coin_toss, 10, replace= TRUE)[y=="Heads"])) #assign vector first
mean(first)

#bimonial

rbinom(20, 4, .2)
table(rbinom(20, 4, .2))
```
```{r simulating from  binomial dist of 10 with p=.42}
x <- 0:10
x

#vector of probabilities from binomial dist of 10
sim <-dbinom(x, 10, .42)
sim
#check to make sure sum=1
sum(sim)

weighted.mean(x,sim)
#varaince
weighted.mean((x-4.2)^2, sim)
#sd
weighted.mean((x-4.2)^2, sim)^.5

#prob histogram
qplot(x,weight=sim, geom="histogram", bins=10)+
  ggtitle("Probability Histogram")

```

```{r my own function}
vals_function<- function(inputs){
  output_something<- do_something(inputs)
  return(output_value)
}

```





